version: "3"

services:
  node:
    image: node
    build:
      context: ./node
    container_name: node
    volumes:
      - node_data:/code
      - ./node:/code
    ports:
      - "3000"
    networks:
      - node-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    
  mysql:
    image: mysql
    build:
      context: ./mysql
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
    tty: true
    
  nginx:
    image: nginx
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - node
    networks:
      - node-network
    ports:
      - "8080:80"
    restart: always

networks:
  node-network:
    driver: bridge

volumes:
  node_data:
  mysql_data: